[package]
name = "water_mark"
version = "0.1.0"
edition = "2024"

[dependencies]
lopdf = "0.33.0"
ab_glyph = "0.2"
log = "0.3.9"


[lib]
name = "water_mark"
crate-type = ["cdylib", "rlib"] # cdylib 用于 PHP (FFI), rlib 用于 main.rs 调用

[[bin]]
name = "water_mark_cli"
path = "src/main.rs"